### ISSUE TITLE
Code review and needed fixes

### ISSUE THREAD

**Issue by sabinaaledort** [openshift-kni/commatrix#3]
* types.go can just be moved to commatrix.go
* same with consts, find the suitable place
* same with static-custom-entries.go, why isn't there a commatrix package dir?
* worth to think about: matrix as a map of comDetails (with proper keys) instead slice
* processeNameFieldIdx typo
* execErr/getErr looks clunky, not sure it is needed (joining it with the outer err)
* oc binary is a prerequisite (for debug package), make sure it is documented /+ installed as part of make
* getPodDefinition could have some cleaning - unnecessary SchedulerName, ServiceAccountName, volumes etc
* getNamespaceDefinition - similarly
* getSecret - can't we use get directly instead of list?
* !strings.Contains(err.Error(), "not found")  - clunky, there's a cleaner way to understand if a resource is missing
* static-custom-entries - is there a reason to keep them string and unmarshaling instead of just having them as the values?
* declare var as empty right before instead of var block in GetIngressEndpointSlicesInfo
* "createEPSliceInfos retrieves lists of" - it doesn't
* getService/getPod - return nil if it doesn't exist instead true/false
* Fix README
* Fix all TODO
* Check if get container funcs can be used to add it to the matrix
* Fix CI and add tests
* Optional:  print matrix only to console (allow optionally printing the additional files)

**Comment by liornoy** [comment]
types.go and consts.go are in different modules to prevent circular dependency between the commatrix and endpointslices.

**Comment by liornoy** [comment]
the reason I made static-custom-entries - as a string is because this is what Yuval suggested me to do when he proposed the idea of allowing users to inject entries into the matrix via a file, and said we will do so for the entries that lack enpointslice. we could change it to go structs and values, but it's just the same and maybe look more crowded.

**Comment by sabinaaledort** [comment]
> as for "oc binary is a prerequisite", as far as I understand, you need a red hat user to download the binary from redhat registry, and it won't be possible from the makefile, so it leaves us with just making sure to document that.

You can get it from the the github repo https://github.com/openshift/oc and add to the Makefile something like https://github.com/openshift/metallb-operator/blob/59584a42af70fb2c13c19ac847094e45fa67a51f/Makefile#L244

**Comment by sabinaaledort** [comment]
> the reason I made static-custom-entries - as a string is because this is what Yuval suggested me to do when he proposed the idea of allowing users to inject entries into the matrix via a file, and said we will do so for the entries that lack enpointslice. we could change it to go structs and values, but it's just the same and maybe look more crowded.

But this file is not the one the user can override. `customEntriesPath` is the add from file, `static-custom-entries.go` file is a static file you are always reading and unmarshaling here https://github.com/openshift-kni/commatrix/blob/ee48bff113682a9623639dfb052273ccecd4dd8d/commatrix/commatrix.go#L56, it's a go file with 
 strings that can be of type ComDetails

**Comment by liornoy** [comment]
> > as for "oc binary is a prerequisite", as far as I understand, you need a red hat user to download the binary from redhat registry, and it won't be possible from the makefile, so it leaves us with just making sure to document that.
> 
> You can get it from the the github repo https://github.com/openshift/oc and add to the Makefile something like https://github.com/openshift/metallb-operator/blob/59584a42af70fb2c13c19ac847094e45fa67a51f/Makefile#L244

done, fixed in the pr

**Comment by oribon** [comment]
> types.go and consts.go are in different modules to prevent circular dependency between the commatrix and endpointslices.

other than `IngressLabel` all of the vars defined in consts.go are used in a single place, when that is the case just declare the consts where you need them. 
Similarly, it seems that the types.go package contains definitions that are all related to commatrix, so just declare them there. If there's some circular dependency it might be worth to think if some packages can be combined together (not always it's right to split packages if stuff are heavily dependant in the first place).

In general, naming a package vaguely ("consts/types/etc.") should be avoided as it is just confusing. A package should have a good reason to exist and when it does it should have a proper name, e.g If there are some "labels" constants that show up in a lot of places (and you do not want to duplicate) then a package holding these constants should be called "labels".

**Comment by sabinaaledort** [comment]
Done
