### ISSUE TITLE
Open issues

### ISSUE THREAD

**Issue by sabinaaledort** [openshift-kni/commatrix#6]
1. Allow setting custom-entries-file in several formats
2. Separate the commatrix to ipv4 and ipv6, can be done with a filed or separated into files
3. Add 6081 port to static entries on MNO only
4. Optional - separate the custom entries file to a temp list (will be cleaned when all the endpointSlices are created) and a static list of ports
5. Review the code - I think there is a failure if ssOutTCP or ssOutUDP is empty
6. Since the ss command is running in threads sometimes the ns is deleted before the pod finished causing the following failure "panic: failed waiting for debug pod to be ready: pods "saledort-virtual-ctlplane-2-karmalabs-corp-debug-l2xlc" not found", need to refactor the whole CreateComDetailsFromNode func
7. And an ignore file for the commatrix-diff-ss file: don't put ovnkube ports in the diff if they are in the NodePort dynamic range (should be 30000 and up but worth checking), ignore also rpc.statd ports, optionally think about  displaying port ranges

**Comment by liornoy** [comment]
re 5: I tried running the program with empty ssOutTCP and ssOutUDP, and didn't get error.

**Comment by sabinaaledort** [comment]
Note for 7: The port range allowed for Services of type NodePort is specified in `serviceNodePortRange` in `networks.config.openshift.io` resource, if it's not set the default of 30000-32767 is used.

**Comment by liornoy** [comment]
Filed a fix for 6. see commit "ss: support concurrent execution" in https://github.com/openshift-kni/commatrix/pull/4/

**Comment by liornoy** [comment]
Filed a fix for 3. see commit "Add MNO only static entry - port 6081"

**Comment by liornoy** [comment]
@sabinaaledort issue no. 7 is fixed by this: https://github.com/openshift-kni/commatrix/pull/10

**Comment by sabinaaledort** [comment]
7 is done in origin-tests to filter the ports we don't want to publish, let's keep the matrix created in the library as genuine as possible

**Comment by sabinaaledort** [comment]
Done
